### PR TITLE
Updated views.py to remove return statements from being inside of else loops.

### PR DESCRIPTION
**Pull request by garrett-rh**
Made a small change by removing return statements from inside of the else portion of if...else statements where the if loop is returning the function. The reason for this is that the "else" does nothing since the if statement would have exited the function otherwise. Removing the "else" will also ensure that the function returns with a value instead of defaulting back to returning a None type. This will help keep undefined behavior at a minimum.

### CODE REVIEW

**Review by PriyanshBordia — CHANGES_REQUESTED** [review]
Check for correctness.!!

**Comment by garrett-rh** [comment]
@PriyanshBordia Just looked over the failing builds and noticed that none of them are failing on the changes I made. Do you have a specific thing in need of correcting? These build checks are also failing on the latest commits to master, as noted by the actions tab. Thanks!

**Comment by garrett-rh** [comment]
Also, just for reference. This is the style issue I am trying to fix.
[https://deepsource.io/gh/PriyanshBordia/Slice-of-a-Pizza/issue/PYL-R1705/occurrences](https://deepsource.io/gh/PriyanshBordia/Slice-of-a-Pizza/issue/PYL-R1705/occurrences)

**Comment by PriyanshBordia** [comment]
Hi - @garrett-rh  I am not actively working on this repository.

**Comment by garrett-rh** [comment]
Hey @PriyanshBordia , understood. I'd still appreciate it if you merged the request since it meets the code standards & suggested practices of one of the bots you use on this repo. Either way, it was great meeting and working with you!

**Pull request closed without merging**
